export const DIAGNOSTIC_SCHEMA = Object.freeze([
    { level: 1, name: 'hydraulic_status', hardware_id: '' },
    { level: 1, name: 'chassis_status', hardware_id: '' },
    { level: 1, name: 'inverter_status', hardware_id: '' },
    { level: 1, name: 'estop_status', hardware_id: '' },
    { level: 1, name: 'robot_status', hardware_id: '' },
    { level: 1, name: 'charger_status', hardware_id: '' },
    { level: 1, name: 'battery_voltage_alarm', hardware_id: '' },
    { level: 1, name: 'overcurrent_alarm', hardware_id: '' },
    { level: 1, name: 'sensor_status', hardware_id: '' },
    { level: 1, name: 'joy_estop', hardware_id: '' },
    { level: 1, name: 'whisker_status', hardware_id: '' },
    { level: 1, name: 'LASER', hardware_id: '' },
    { level: 1, name: 'PLC', hardware_id: '' },
    { level: 1, name: 'CAMERA', hardware_id: '' },
    { level: 1, name: 'IMU', hardware_id: '' },
    { level: 1, name: 'TF', hardware_id: '' },
    { level: 1, name: 'TF0', hardware_id: '+' },
    { level: 2, name: 'temperature_motor_left', hardware_id: '\u00b0C' },
    { level: 2, name: 'temperature_motor_right', hardware_id: '\u00b0C' },
    { level: 2, name: 'temperature_drive_left', hardware_id: '\u00b0C' },
    { level: 2, name: 'temperature_drive_right', hardware_id: '\u00b0C' },
    { level: 2, name: 'battery_voltage', hardware_id: 'V' },
    { level: 2, name: 'battery_current', hardware_id: 'A' },
    { level: 2, name: 'hydraulic_voltage', hardware_id: 'V' },
    { level: 2, name: 'chassis_voltage', hardware_id: 'V' },
    { level: 2, name: 'inverter_voltage', hardware_id: 'V' },
    { level: 2, name: 'inverter_voltage_a', hardware_id: 'V' },
    { level: 2, name: 'inverter_voltage_b', hardware_id: 'V' },
    { level: 2, name: 'inverter_voltage_c', hardware_id: 'V' },
    { level: 2, name: 'inverter_current_a', hardware_id: 'A' },
    { level: 2, name: 'inverter_current_b', hardware_id: 'A' },
    { level: 2, name: 'inverter_current_c', hardware_id: 'A' },
    { level: 2, name: 'vacuum1_pressure', hardware_id: 'KPa' },
    { level: 2, name: 'vacuum_pressure', hardware_id: 'KPa' },
    { level: 2, name: 'temperature', hardware_id: '\u00b0C' },
    // { level: 2, name: 'TF2', hardware_id: '-' },
    // { level: 2, name: 'TF3', hardware_id: '+' },
    // { level: 2, name: 'TF4', hardware_id: '-' },
    // { level: 2, name: 'TF5', hardware_id: '+' },
    // { level: 2, name: 'TF6', hardware_id: '-' },
    // { level: 2, name: 'TF7', hardware_id: '+' },
]);
