syntax = "proto3";

package robot.diagnostics;

message Time {
  uint32 secs = 1;
  uint32 nsecs = 2;
}

message Header {
  uint32 seq = 1;
  Time stamp = 2;
  string frame_id = 3;
}

message KeyValue {
  string key = 1;
  string value = 2;
}

message DiagnosticStatus {
  uint32 level = 1;
  uint32 name = 2;
  string message = 3;
  string hardware_id = 4;
  repeated KeyValue values = 5;
}

message DiagnosticArray {
  Header header = 1;
  repeated DiagnosticStatus status = 2;
}

message DiagnosticMessage {
  uint64 timestamp = 1;
  DiagnosticArray message = 2;
}